sudo: false
addons:
  apt:
    packages:
    - zlibc
    - curl
    - libssl0.9.8
    - libbz2-dev 
    - libxslt1-dev
    - libxml2-dev
    - python-gevent
    - libhdf5-serial-dev
    - netcdf-bin
    - libnetcdf-dev
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
  - pypy3
# command to install dependencies
install:
  - "make deploy"
# command to run tests
script: "make test-coverage-travis-ci" #nosetests
after_success:
  - "make test-coveralls"
